# Generated by Django 2.2.26 on 2022-01-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20220121_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='is_new_building',
            field=models.NullBooleanField(verbose_name='Новостройка'),
        ),
    ]
