# Generated by Django 2.2.26 on 2022-01-21 04:47

from django.db import migrations


def fill_is_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(is_new_building=True)
    Flat.objects.filter(construction_year__lt=2015).update(is_new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_is_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_is_new_building),
    ]
