# Generated by Django 2.2.24 on 2022-01-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_new_model_complaint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'verbose_name': 'Жалобы', 'verbose_name_plural': 'Жалобы'},
        ),
        migrations.AlterModelOptions(
            name='flat',
            options={'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
    ]
