# Generated by Django 2.2.26 on 2022-01-23 13:07

from django.db import migrations


def refactoring_owner(apps, schema_editor):
    """Очищаем таблицу собственников в БД от дублей приняв за условие,
    что запись в таблице с одинаковым ФИО это один и тот же человек.
    Этот человек может иметь несколько разных телефонов,
    поэтому другой телефон добавляем в новое поле: "Добавочный телефон":
    (additional_phone_number)"""
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_owner'),
    ]

    operations = [
        migrations.RunPython(fill_flats_field),
    ]