# Generated by Django 2.2.24 on 2022-02-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20220127_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='is_new_building',
            field=models.NullBooleanField(db_index=True, verbose_name='Новостройка'),
        ),
    ]
